# Generated by Django 5.2.14 on 2026-05-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='subscription_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='subscription_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
