# Generated by Django 5.2.14 on 2026-05-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0004_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='parameters',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
