# Generated by Django 5.2.14 on 2026-05-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0006_notification_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='category',
            field=models.CharField(choices=[('model', 'AI Model'), ('tool', 'AI Araç')], default='model', max_length=20),
        ),
    ]
