# Generated by Django 5.2.14 on 2026-05-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0009_reviewlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='strengths',
            field=models.TextField(blank=True, help_text='Her maddeyi virgülle ayır'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='weaknesses',
            field=models.TextField(blank=True, help_text='Her maddeyi virgülle ayır'),
        ),
    ]
