# Generated by Django 5.2.14 on 2026-05-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0010_aimodel_strengths_aimodel_weaknesses'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('username', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(max_length=100)),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
