# Generated by Django 5.2.14 on 2026-05-30 17:10

import models_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0011_securitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=models_app.models.avatar_upload_path),
        ),
    ]
